#!/bin/sh
# changed for Termux that doesn't support gcc and nested functions
# -std=c++11 ???
clang++ -Wno-deprecated -Wno-writable-strings -DHTTPD jml.c httpd.c && mv a.out ./jml && ./jml $*

# notice, we make the compiler generate 4b longs...
#gcc -m32 -DHTTPD jml.c httpd.c && mv a.out ./jml && ./jml $*
